stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/your-username/your-project-name

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .

test:
  stage: test
  script:
    - python -m pytest

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker push $IMAGE_NAME